### ISSUE TITLE
Source input polygon class statistics (multiple tif)

### ISSUE THREAD

**Issue by Pratyush1991** [remicres/otbtf#12]
Hello,

Is it possible to provide multiple tif files i.e different dates (time series and let say each tif file has 4 bands) as an input for polygonclass statistics..? Or all the tif files should be stacked to one tif file for input.?

As I read from the description it is mentioned that the input can be list of images. I did try the same by providing two tifs as input (each has 4 bands) but when I checked the xml i.e output file the number of samples per classes is same, if I provide one tiff or two tif files as input. The number of samples per class should be more if two tifs are provided as input..? The command I used is as below 

`sudo docker run -u otbuser -w="/home/otbuser/" -v $(pwd):/home/otbuser mdl4eo/otbtf1.7:gpu otbcli_PolygonClassStatistics -vec /home/otbuser/Data/Pookwe/Shapefiles/Ratoon_Jan_Feb_Mar1_reprojected.shp -field Class -in $"/home/otbuser/Data/Pookwe/Images/SENTINEL2A_20180323-033825-637_L2A_T47QRU_stacked.tif" "/home/otbuser/Data/Pookwe/Images/Ratoon_Mar1_2018.tif" -out /home/otbuser/Output/1.Polygon_stats/vec_stats_objid_new.xml
`

**Comment by remicres** [comment]
The `PolygonClassStatistics` application uses only the input image for its metadata (spatial extend, pixels size, etc).
That's why you have the same result using 1 or N stacked images.
The number of samples per class isn't affected by the number of images.
The `PolygonClassStatistics` application is part of the official OTB, so I would recommend to post any related questions on the official forum.

**Comment by Pratyush1991** [comment]
Thank you so much for the information.
