### ISSUE TITLE
Error otbuser

### ISSUE THREAD

**Issue by diouck** [remicres/otbtf#16]
Hello
I am trying out the application. After an installation with Docker, I try to follow the tutorial. 

https://mdl4eo.irstea.fr/2019/01/04/an-introduction-to-deep-learning-on-remote-sensing-images-tutorial/

First, when I launch a command all alone it does not work for example: otbcli_BandMathX
Is this normal or must always add docker run -u otbuser -v $ (pwd): / home / otbuser mdl4eo / otbtf1.7: cpu ...?

And the other error that I encounter, the user cannot access the files when I issue this command

```
otbcli_BandMathX \
-il T54SUE_20190508T012701_B04_10m.jp2 \
    T54SUE_20190508T012701_B03_10m.jp2 \
    T54SUE_20190508T012701_B02_10m.jp2 \
    T54SUE_20190508T012701_B08_10m.jp2 \
-exp "{im1b1/im1b1Maxi;im2b1/im2b1Maxi;im3b1/im3b1Maxi;im4b1/im4b1Maxi}" \
-out Sentinel-2_B4328_10m.tif
```
To debug, I create an otbuser sudo user but I have this error

`docker: Error response from daemon: unable to find user otbuser: no matching entries in passwd file.
ERRO[0001] error waiting for container: context canceled
`

**Comment by remicres** [comment]
Your issue is related to the use of docker. If you want to follow the entire tutorial, it might be more easy to enter interactive mode. 

First, enter the docker image in interactive mode:

```
docker run -ti -v /path/to/local1:/path/to/mount1 -v /path/to/local2:/path/to/mount2 mdl4eo/otbtf1.7:cpu bash
```

Note that you might need to `sudo` before the command depending of your user rights.
Then you can follow the tutorial. Now, the `cd` command will be persistent in your session, as any bash session. You can then go in the downloaded Sentinel-2 image folder, run BandMathX, etc.
During the interactive session, you can also add a new user, modify the image locally, then commit your changes of the docker image (search `docker commit` on the web).

Look at the closed issues about docker usage, some help was been provided to other users.

**Comment by diouck** [comment]
hank you it's cool, By executing this command
`docker run -ti -v /home/otbuser:/home/otbuser mdl4eo/otbtf1.7:cpu bash`
I succeeded in doing the rework. But during the training of the model, I cannot execute the command,
Despite the explanations do you have an idea to configure the variable PYTHONPATH to recover tricks
`
Traceback (most recent call last):
  File "create_model1.py", line 1, in <module>
    from tricks import *
ModuleNotFoundError: No module named 'tricks'`

Thanks

**Comment by remicres** [comment]
You must add the parent directory of `tricks.py`to the `PYTHONPATH` environment variable before running the python commands.

```
export PYTHONPATH=$PYTHONPATH:/work/otb/otb/Modules/Remote/otbtf/python
```

You can add the above command to you `bashrc` file in order to set the `PYTHONPATH` permanently (don't forget to `docker commit` your changes after that)
