### ISSUE TITLE
Using Sentinel-1

### ISSUE THREAD

**Issue by lolob** [remicres/otbtf#17]
Hello,
I am a beginner. I followed carefully the simple-cnn as shown in the tutorial but with the Sentinel-1 SAR data instead. The image used is RGB composite (R:VV,G:VH,B:VV). After export to image from SNAP7.0, I have 4 bands (extra band is alpha). I manually created 3 classes (water,urban,forest) within the same AOI on the image. Modified the simple-cnn script with the 3 classes. I run step by step until otbcli_TensorflowModelServe. However, the result is not as expected. First, I thought maybe the patches 16x16 was too small for Sentinel-1 since it is different from the normal optical. So, I changed to 512x512 and re-do all the steps again from the start. Do i need to change some lines in the simple-cnn script too? Other question is about the TensorflowModelServe: Receptive field [16, 16]. If I changed Receptive field to [32, 32], I got  `Error occured during tensor to image conversion`. If I changed Receptive field to [512, 512], I got `Allocation of 1040449536 exceeds 10% of system memory.` If I changed them to [8, 8], I got ` Can't run the tensorflow session !`.  Has anyone tried using OTBTF with Sentinel-1 SAR? Thank you.

**Comment by remicres** [comment]
- You should use as input image a 2-channels image instead. In addition you might give a try with SAR images in dB to see if the model performs better (quite plausible). Just change the last dimension of the placeholder of the input image (2 instead of 4). 

- 512x512 patches is way too large. Start with a small patch e.g. 16x16 is enough.
- The expression field is the volume that the net modifies in the output space. In patch-based approach, the model estimates 1 single label value for the input patch. Hence the expression field is 1x1. Your net must fulfill this requirement (i.e. 16x16 input --> 1x1 output). If not, you will likely have an error message. If you change the input patches size, you must ensure that the output of the net is 1x1 (play with the number of convolutions, stride, kernel size, to change that). Expression field is mostly used when model estimates an output image rather that a single valued pixel, so in your case you should not change it.

**Comment by lolob** [comment]
Thank you for the reply. I tried again with the recommendations but still got unconvincing result as shown in the picture here. The 2-channels image are Sigma0_VH_db and Sigma0_VV_db which was exported from SNAP7.0. 
![qgis](https://user-images.githubusercontent.com/15963902/75948294-0b168f80-5ede-11ea-9815-877e594545c8.png)

**Comment by remicres** [comment]
Is your dB image normalized properly? SAR dB values are usually in the [-40, 0] range: you might need to normalize differently than optical images.
To use the provided networks without changing weights initialization, requires that your data is properly normalized, in your case in the [-1, 0] range.
Changing the BandMathX expression during the normalization step should do the trick, for instance with the following expression `{im1b1/im1b1Mini;im1b2/im1b2Mini}` or something like that.
Also check that your patches (images and labels) contain correct values before training.

**Comment by lolob** [comment]
These are the list files of the datasets:

`Sigma0_VH.hdr  Sigma0_VH.img  Sigma0_VH_db.hdr  Sigma0_VH_db.img  Sigma0_VV.hdr  Sigma0_VV.img  Sigma0_VV_db.hdr  Sigma0_VV_db.img`

To get the [-1, 0] range I use the following:
```
otbcli_BandMathX \
> -il Sigma0_VH_db.img \
> Sigma0_VV_db.img \
> -exp "{(im1b1-im1b1Mini) * (0 -(-1)) / (im1b1Maxi-im1b1Mini) + (-1);(im2b1-im2b1Mini) * (0 -(-1)) / (im2b1Maxi-im2b1Mini) + (-1)}" \
> -out /home/root/sentinel/otbtf/Sentinel-1v3_VHVV.tif
```
So the result of BandMathX is:
![qgis](https://user-images.githubusercontent.com/15963902/75958659-a5370180-5ef7-11ea-9b5a-bdc46d062e92.png)

That should do it, right?

**Comment by remicress** [comment]
Looks great. The important thing is that the absolute values are in the [0,1]  range, you dont have to substract 1 in your formula (I meant [-1,0] because SAR dB values are usually <0)

**Comment by lolob** [comment]
Thanks @remicres for the lesson. I finally got the output. Not great but it is a learning process for me. One more question, let say I want to increase the input patch size as 32x32 or 64x64. Where do I go next?

**Comment by remicres** [comment]
From here, it's up to you... I recommend reading a few articles/blogs and, of course, experiment ;)
