### ISSUE TITLE
getting errors when building otbtf

### ISSUE THREAD

**Issue by MoslemTCM** [remicres/otbtf#3]
I am trying yo build the otbtf library in ubuntu 18 and I am getting the following errors when running:
make -j $(grep -c ^processor /proc/cpuinfo)

/usr/include/c++/7/ostream:682:5: note:   template argument deduction/substitution failed:
/usr/include/c++/7/ostream: In substitution of ‘template<class _Ostream, class _Tp> typename std::enable_if<std::__and_<std::__not_<std::is_lvalue_reference<_Tp> >, std::__is_convertible_to_basic_ostream<_Ostream>, std::__is_insertable<typename std::__is_convertible_to_basic_ostream<_Tp>::__ostream_type, const _Tp&, void> >::value, typename std::__is_convertible_to_basic_ostream<_Tp>::__ostream_type>::type std::operator<<(_Ostream&&, const _Tp&) [with _Ostream = std::basic_ostream<char>&; _Tp = std::vector<itk::Size<2>, std::allocator<itk::Size<2> > >]’:
/opt/moslem-git/OTB/otb/Modules/Remote/include/otbTensorflowMultisourceModelBase.h:129:3:   required from ‘void otb::TensorflowMultisourceModelBase<TInputImage, TOutputImage>::SetOutputExpressionFields(otb::TensorflowMultisourceModelBase<TInputImage, TOutputImage>::SizeListType) [with TInputImage = otb::VectorImage<float, 2>; TOutputImage = otb::VectorImage<float, 2>; otb::TensorflowMultisourceModelBase<TInputImage, TOutputImage>::SizeListType = std::vector<itk::Size<2>, std::allocator<itk::Size<2> > >; typename TInputImage::SizeType = itk::Size<2>]’
/opt/moslem-git/OTB/otb/Modules/Remote/app/otbTensorflowModelTrain.cxx:454:75:   required from here
/usr/include/c++/7/ostream:682:5: error: no type named ‘type’ in ‘struct std::enable_if<false, std::basic_ostream<char>&>’
/opt/moslem-git/OTB/otb/Modules/Remote/include/otbTensorflowMultisourceModelBase.h: In instantiation of ‘void otb::TensorflowMultisourceModelBase<TInputImage, TOutputImage>::SetOutputExpressionFields(otb::TensorflowMultisourceModelBase<TInputImage, TOutputImage>::SizeListType) [with TInputImage = otb::VectorImage<float, 2>; TOutputImage = otb::VectorImage<float, 2>; otb::TensorflowMultisourceModelBase<TInputImage, TOutputImage>::SizeListType = std::vector<itk::Size<2>, std::allocator<itk::Size<2> > >; typename TInputImage::SizeType = itk::Size<2>]’:
/opt/moslem-git/OTB/otb/Modules/Remote/app/otbTensorflowModelTrain.cxx:454:75:   required from here
/usr/include/c++/7/ostream:574:5: note: candidate: template<class _Traits> std::basic_ostream<char, _Traits>& std::operator<<(std::basic_ostream<char, _Traits>&, const unsigned char*)

and 

/opt/moslem-git/OTB/otb/Modules/Remote/include/otbTensorflowMultisourceModelBase.h: In instantiation of ‘void otb::TensorflowMultisourceModelBase<TInputImage, TOutputImage>::SetOutputExpressionFields(otb::TensorflowMultisourceModelBase<TInputImage, TOutputImage>::SizeListType) [with TInputImage = otb::VectorImage<float, 2>; TOutputImage = otb::VectorImage<float, 2>; otb::TensorflowMultisourceModelBase<TInputImage, TOutputImage>::SizeListType = std::vector<itk::Size<2>, std::allocator<itk::Size<2> > >; typename TInputImage::SizeType = itk::Size<2>]’:
/opt/moslem-git/OTB/otb/Modules/Remote/app/otbTensorflowModelTrain.cxx:454:75:   required from here
/opt/moslem-git/OTB/otb/Modules/Remote/include/otbTensorflowMultisourceModelBase.h:129:3: error: no match for ‘operator<<’ (operand types are ‘std::basic_ostream<char>’ and ‘const SizeListType {aka const std::vector<itk::Size<2>, std::allocator<itk::Size<2> > >}’)
   itkSetMacro(OutputExpressionFields, SizeListType);

Do you have any idea how I can resolve these two problems. Thanks!

OTB version: 6.6.0
Tensorflow version: 1.3.1

**Comment by remicress** [comment]
Can you give a try with otb "develop" branch ? (6.6 is quite old)

**Comment by MoslemTCM** [comment]
@remicress: I build the project with the develop brach but I still get the same errors.
Bazel version: 0.25.2
TensorFlow versioin: r1.14
gcc version: 7.4.0
cmake version: 3.10.2

**Comment by remicres** [comment]
@MoslemTCM **in short**:

1. Please check the otbtf version
2. Can you try to build against commit 0df44b312d64d6c3890b65d3790d4a17d0fd5f23 of otb develop?

**In detail**:
Your error mentions `itkSetMacro(OutputExpressionFields, SizeListType)` of `otbTensorflowMultisourceModelBase.h:129` : this is strange because there is no such in L129 of both `develop` or `master` branches of otbtf. Can you please check your versions of otbtf?

On my side, I tried to reproduce the issue using:
- DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
- gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04)
- otb `develop` branch 
- otbtf `develop` or `master` branch
-TensorFlow r1.14

I can't complile otbtf since [this MR](https://gitlab.orfeo-toolbox.org/orfeotoolbox/otb/merge_requests/484) removes `SetDocName`. I'll push a fix quickly for that.
I built successfully otbtf from this commit of otb: 0df44b312d64d6c3890b65d3790d4a17d0fd5f23
 (Go in the otb src dir and do a `git checkout 0df44b312d64d6c3890b65d3790d4a17d0fd5f23` then rebuild)

From this commit you should be able to build otb/otbtf.

**Comment by MoslemTCM** [comment]
Thank you very much for your help. Now I am able to successfully build the project.
It appears that I was using the ITK version 1.13 included in the SuperBuild folder. However, you used
the version 1.12 installed using libinsighttoolkit4-dev to build the project.
