### ISSUE TITLE
Partial install

### ISSUE THREAD

**Issue by joaquinperaza** [remicres/otbtf#37]
If I have installed tensorflow for NVIDIA jetson nano, from nvidia platform (1.X), can I build from source omitting tensorflow installation?
Thanks.

**Comment by remicres** [comment]
Hi,
I really don't know this system.

In order to build OTBTF with TensorFlow, you must have the following:
- `libtensorflow_cc.so`
- `libtensorflow_framework.so`
- TensorFlow `include` directory

I suggest you take a look in the dockerfiles (`tools/dockerfiles` of OTBTF repository) to see how it is done from scratch. Maybe you just have to collect the TensorFlow headers, and (re) build the missing libraries.
