### ISSUE TITLE
Method for normalization of Time Series Images

### ISSUE THREAD

**Issue by Pratyush1991** [remicres/otbtf#40]
Hello Remi,

I have a few question regarding the normalization procedure for time series data. I'm not sure if the process is correct or different from what I understand. Let say I have a time series image of 3 spectral bands (B, G, NIR) and 1 vegetation indices (NDVI) stacked together for 10 dates (Total of 40 bands). Normally I use OTB's BandmathX or DynamicConvert to  rescale all the bands between 0, 1. I assume this process calculates the mean and std. for each date for each band and then it uses it to normalize.

But I wonder as mentioned in paper [M3Fusion](https://www.researchgate.net/publication/323597473_M3Fusion_A_Deep_Learning_Architecture_for_Multi-ScaleModalTemporal_satellite_data_fusion) " The values were normalized in the interval [0,1] by spectral band" and [DuPLO](https://www.sciencedirect.com/science/article/pii/S0924271619300115) "The values are normalized, per band (resp. indices) considering the time series, in the interval ."  Does this mean I should calculate the mean and std. dev for each feature (B, G, NIR, and NDVI) for whole time series date (all 10 dates) and then normalize each date based on that mean and std. dev .? 
Let me know what you feel is best approach.

Thanking you,
Pratyush

**Comment by remicres** [comment]
Hi @Pratyush1991 ,

Apology for the delay I just have noticed this issue!

To answer your question: you must normalize each band separately, based on their statistics. Of course, you can compute mean/std along all dates for {B, G, NIR, NDVI} respectively, like it is meant in the paper.

Personally, I like to consider that a given network aims to generalize to any image for a given sensor (even if, the network needs some re-training, or some fine tuning). For Sentinel-2 for instance, I never compute mean/std statistics: instead, I normalize the pixel values so that they fit in the [0, 1] range, simply by rescaling/clipping pixels from the [0, 10000] range for instance. I read a few paper where the authors do the same!
This way, suppose that you have a new image suited to be processed, then you don't have to update the statistics, just train or apply the network. It is much straightforward !

Hope that helps :smiley:

**Comment by Pratyush1991** [comment]
Thank you so much @remicres. Your answer was helpful.
