### ISSUE TITLE
Some querries related to Otbtf on Docker.

### ISSUE THREAD

**Issue by Pratyush1991** [remicres/otbtf#7]
Hello, 

As I find building Otbtf on Docker simpler and easier as compared to building natively. So I have some queries as follows

1) Why is OTB and Tensorflow built with minimal optimization flag ? Will it be possible to build with those flags enabled or may be if you can provide some guide on how to build with those flags enabled ?

2) How different is  Docker Otbtf built with minimal optimization as compared to building it natively ?  Also are there any limitations or things that one should be aware of when using Otbtf on docker ?

3) I just wonder if this can be possible, it would be easier if one could just pull fully built Otbtf docker image and rather than building from docker file. As because I could build this on my desktop machine which is a bit powerful as compared to my laptop configuration. In my laptop(i5 with 8GB RAM) build process was very slow so I had to cancel it.

**Comment by remicres** [comment]
>Why is OTB and Tensorflow built with minimal optimization flag ? Will it be possible to build with those flags enabled or may be if you can provide some guide on how to build with those flags enabled ?

Because it's the easiest setup, and it's intended to be built on all possible hardware. I hope some people will contribute to this repository adding more dockers with interesting setups (e.g. CUDA)

> How different is Docker Otbtf built with minimal optimization as compared to building it natively ? Also are there any limitations or things that one should be aware of when using Otbtf on docker ?

Well, I am not a docker expert. On UNIX systems, probably no that much different. I never tried the GPU or MPI support inside a docker, but I guess this should work fine.

> I just wonder if this can be possible, it would be easier if one could just pull fully built Otbtf docker image and rather than building from docker file. As because I could build this on my desktop machine which is a bit powerful as compared to my laptop configuration. In my laptop(i5 with 8GB RAM) build process was very slow so I had to cancel it.

I guess that this should be possible, but I don't know how. Put images on Dockerhub or something like that? It could be great if somebody knowing well those things could help, I agree.

**Comment by Pratyush1991** [comment]
Thank you so much.
