### ISSUE TITLE
How to set parameters"-source1.rfieldx" "-source1.rfieldy" and "-output.efieldx" "-output.efieldy" in otbcli_TensorflowModelServe

### ISSUE THREAD

**Issue by chingrun** [remicres/otbtf#8]
Hello, I used otbtf to train my own model, and i got *.pb and the variable files, but when i use otbcli_TensorflowModelServe to infer, errors showed about "-source1.rfieldx" "-source1.rfieldy" and "-output.efieldx" "-output.efieldy". I am curious about how to set the parameter, in the paper i found the corresponding parameters were set to 80 and 16, how can i set the parameter in my own model? Thanks!

**Comment by remicres** [comment]
Hi,
These parameters depends on your deep net.
The "receptive field" (_rfield_) corresponds to the input volume that "sees" the deep net.
The "expression field" (_efield_) corresponds to the output volume that the deep net will create.

For instance:
-  if your network performs single pixel classification (I called this "patch-based") e.g. it predict the class for the central pixel of a 16x16 patch, then your expression field is 1x1 (because your network generates 1 pixels for one input patch) and your receptive field is 16x16 (because your network inputs 16x16 pixels patches of input image).
-  if your network performs semantic segmentation, you will likely have some expression field with a size > 1. For instance the fully convolutional network that you mention ("Maggiori" network in the paper) has a receptive field of 80x80 pixels and an expression field of 16x16. 

You _rfield_ and _efield_ values (and _spcscale_ if your net does change the physical spacing of the output) must be consistent with the model that you want to run.

I know I should put more documentation about the models provided in the repository. There is many examples to provide, to explain entirely how deep nets can be applied. I promise to add this very soon!

**Comment by remicres** [comment]
Just added some new documentation in `doc/EXAMPLES.md`

**Comment by chingrun** [comment]
Thank you for your kind help! @remicres
