### ISSUE TITLE
OTBTF.remote.cmake

### ISSUE THREAD

**Issue by lef-t** [remicres/otbtf#9]
Hello, 

I have built OTB and Tensorflow but i have problem to build OTBTF as a remote module. In particular i can't find the OTBTF.remote.cmake. Any help?

Thanks a lot :)

**Comment by remicres** [comment]
Since OTBTF is not an official remote module of OTB, there is no OTBTF.remote.cmake right now.

But you should be able to build without it.
What you can do is to clone the OTBTF repository in the `otb/Modules/Remote` folder. 
Then you go in your `build/OTB/build` directory and re-configure/rebuild OTB. 
(All these steps are described in the dockerfile: see [here](https://github.com/remicres/otbtf/blob/1dac6c4d9455a63693adc2c87af1ef7fcc2f72eb/tools/dockerfiles/bionic.tf-r1.14.otb-develop/Dockerfile#L166))
